### ISSUE TITLE
crazy "15n vs nlogn" graphs at 1.3, figure 1.5

### ISSUE THREAD

**Issue by Groxx** [patmorin/ods#26]
There seems to be something wrong with figure 1.5, which is about half-way down the page on [chapter 1.3](http://opendatastructures.org/ods-java/1_3_Mathematical_Background.html).  I see this on both Chrome and Firefox:
![crazy graph](http://f.cl.ly/items/0g0c2L1M3M1J2C1Y1m0T/Screenshot%202015-01-18%2013.49.50.jpg)

**Comment by patmorin** [comment]
Yes, latex2html doesn't handle everything perfectly. I'll see if I can fix this the next time I'm doing a major update.

**Comment by patmorin** [comment]
I'm closing now since we'll be moving away from LaTeX2HTML shortly.
