### ISSUE TITLE
PDFs contain no table of contents

### ISSUE THREAD

**Issue by dimonomid** [patmorin/ods#27]
The pdf files contain no table of contents. I mean, well, there IS table of contents as just a lot of hyperreferences in the beginning of the document, but there's no table of contents that pdf viewer is aware of.

It is a pain to navigate especially if I use pocket book device.

And thank you very much for this project, it is really incredible. Thanks.

**Comment by patmorin** [comment]
I've recompiled and reinstalled the PDFs at opendatastructures.org, which now seem to have proper indexes.  I'm not sure why the previous ones didn't.
