### ISSUE TITLE
Fail to make ods document

### ISSUE THREAD

**Issue by EvanMisshula** [patmorin/ods#32]
I am having a problem making the odds document.  I am on OS X 10.10.  The make fails to make the figures.  When I try to use ipetoipe -pdf on a single figure, for example 24rb.ipe, it returns

bash-3.2$ ipetoipe -pdf 24rb.ipe 
Document 24rb.ipe has 1 pages (3 views)
There were Latex errors.

If I load the figure into ..ipe.. and run latex from inside ..ipe..I get:

(/Users/emisshula/Library/texmf/tex/latex/ods/ods-colors.sty

! LaTeX Error: Option clash for package xcolor.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              

l.3 \definecolor
                {keyword}{named}{RoyalPurple}
The package xcolor has already been loaded with options:
  []
There has now been an attempt to load it with options
  [usenames,dvipsnames]
Adding the global options:
  ,usenames,dvipsnames
to your \documentclass declaration may fix this.
Try typing  <return>  to proceed.

! Package xcolor Error: Undefined color `RoyalPurple'.

If I try to run a minimal document using dos-colors:

\documentclass{article}
\usepackage{ods-colors}
\begin{document}
Hello, World!
\end{document}

It writes without error.  Any guidance would be appreciated.  Thank you.

**Comment by lam2mo** [comment]
I am getting a similar error on Linux Mint:

    $ ipetoipe -pdf 24rb.ipe 
    Document 24rb.ipe has 1 pages (3 views)
    There were Latex errors.

As the original commenter, I tried running within the graphical Ipe editor, but I got a different error:

    ! LaTeX Error: File `kpfonts.sty' not found.

Is there perhaps some latex package that we are both missing?

**Comment by EvanMisshula** [comment]
@lam2mo, Were you able to run the minimal doc that I posted without error?

**Comment by lam2mo** [comment]
@EvanMisshula: I tried, and got a LaTeX error about xcolor.sty not being found. I became quite suspicious of Linux Mint's installation of LaTeX at that point and poked around a bit, discovering that by default, the full texlive-full package is NOT installed. After several hours of downloading packages and a few minutes of running "make" again, it does seem to have built the final PDFs (ods-python.pdf, etc.). So it seems that my issue was indeed a LaTeX package problem.

Since you're on Mac, I assume that you're using MacTex. I forget exactly how the package management works for that system, but I'd suggest trying to install *everything* that the system provides, especially any color-related package.

**Comment by EvanMisshula** [comment]
@lam2mo Thanks. I am still out of luck.

**Comment by maknahar** [comment]
While Running make in Ubuntu 14.04, I am getting following error

~/work/projects/go/src/ods$ make
(cd java ; make)
make[1]: Entering directory `/home/vembu/work/projects/go/src/ods/java'
javac ods/*.java
jar cvf ods.jar ods/*.class
added manifest
adding: ods/AdjacencyLists.class(in = 2191) (out= 1237)(deflated 43%)
adding: ods/AdjacencyMatrix.class(in = 2074) (out= 1111)(deflated 46%)
adding: ods/Algorithms.class(in = 6664) (out= 3316)(deflated 50%)
adding: ods/ArrayDeque.class(in = 2109) (out= 1100)(deflated 47%)
adding: ods/ArrayQueue$1QueueIterator.class(in = 1035) (out= 627)(deflated 39%)
adding: ods/ArrayQueue.class(in = 2675) (out= 1493)(deflated 44%)
adding: ods/ArrayStack.class(in = 2482) (out= 1318)(deflated 46%)
adding: ods/BTree$BTIterator.class(in = 2510) (out= 1363)(deflated 45%)
adding: ods/BTree$DuplicateValueException.class(in = 351) (out= 255)(deflated 27%)
adding: ods/BTree$Node.class(in = 2817) (out= 1493)(deflated 47%)
adding: ods/BTree.class(in = 8623) (out= 4287)(deflated 50%)
adding: ods/BinaryHeap$1PQI.class(in = 893) (out= 559)(deflated 37%)
adding: ods/BinaryHeap.class(in = 5362) (out= 2711)(deflated 49%)
adding: ods/BinarySearchTree$1BTI.class(in = 1329) (out= 673)(deflated 49%)
adding: ods/BinarySearchTree$BSTNode.class(in = 496) (out= 295)(deflated 40%)
adding: ods/BinarySearchTree.class(in = 5968) (out= 2536)(deflated 57%)
adding: ods/BinaryTree$BTNode.class(in = 451) (out= 281)(deflated 37%)
adding: ods/BinaryTree.class(in = 3076) (out= 1541)(deflated 49%)
adding: ods/BinaryTrie$1.class(in = 735) (out= 437)(deflated 40%)
adding: ods/BinaryTrie$1I.class(in = 622) (out= 378)(deflated 39%)
adding: ods/BinaryTrie$1N.class(in = 437) (out= 298)(deflated 31%)
adding: ods/BinaryTrie$Nöde.class(in = 1050) (out= 569)(deflated 45%)
adding: ods/BinaryTrie$TrieIterator.class(in = 1021) (out= 593)(deflated 41%)
adding: ods/BinaryTrie.class(in = 6971) (out= 3341)(deflated 52%)
adding: ods/BlockStore.class(in = 1381) (out= 747)(deflated 45%)
adding: ods/ChainedHashTable$1IT.class(in = 1394) (out= 792)(deflated 43%)
adding: ods/ChainedHashTable.class(in = 2848) (out= 1603)(deflated 43%)
adding: ods/DLList$Iterator.class(in = 1787) (out= 909)(deflated 49%)
adding: ods/DLList$Node.class(in = 464) (out= 304)(deflated 34%)
adding: ods/DLList.class(in = 2390) (out= 1166)(deflated 51%)
adding: ods/DefaultComparator.class(in = 523) (out= 305)(deflated 41%)
adding: ods/DualArrayDeque.class(in = 2898) (out= 1483)(deflated 48%)
adding: ods/DualRootishArrayDeque.class(in = 587) (out= 360)(deflated 38%)
adding: ods/Factory.class(in = 948) (out= 504)(deflated 46%)
adding: ods/FastArrayStack.class(in = 1297) (out= 733)(deflated 43%)
adding: ods/FastSqrt.class(in = 1910) (out= 1164)(deflated 39%)
adding: ods/Graph.class(in = 370) (out= 245)(deflated 33%)
adding: ods/HashTable$1IT.class(in = 1342) (out= 781)(deflated 41%)
adding: ods/HashTable.class(in = 3389) (out= 1865)(deflated 44%)
adding: ods/Integerizer.class(in = 230) (out= 155)(deflated 32%)
adding: ods/LinearHashTable$1IT.class(in = 1157) (out= 672)(deflated 41%)
adding: ods/LinearHashTable.class(in = 16711) (out= 10387)(deflated 37%)
adding: ods/MeldableHeap$1MHI.class(in = 1292) (out= 684)(deflated 47%)
adding: ods/MeldableHeap$Node.class(in = 454) (out= 288)(deflated 36%)
adding: ods/MeldableHeap.class(in = 6243) (out= 3049)(deflated 51%)
adding: ods/MultiplicativeHashMap.class(in = 1370) (out= 668)(deflated 51%)
adding: ods/MultiplicativeHashSet.class(in = 2149) (out= 1195)(deflated 44%)
adding: ods/Pair.class(in = 661) (out= 405)(deflated 38%)
adding: ods/RangeSSet$1IT.class(in = 1437) (out= 777)(deflated 45%)
adding: ods/RangeSSet.class(in = 2772) (out= 1287)(deflated 53%)
adding: ods/RedBlackTree$Node.class(in = 452) (out= 288)(deflated 36%)
adding: ods/RedBlackTree.class(in = 6833) (out= 3389)(deflated 50%)
adding: ods/RootishArrayStack.class(in = 2248) (out= 1251)(deflated 44%)
adding: ods/SEList$BDeque.class(in = 658) (out= 424)(deflated 35%)
adding: ods/SEList$Location.class(in = 548) (out= 346)(deflated 36%)
adding: ods/SEList$Node.class(in = 526) (out= 326)(deflated 38%)
adding: ods/SEList.class(in = 4807) (out= 2518)(deflated 47%)
adding: ods/SLList$1SLIterator.class(in = 989) (out= 590)(deflated 40%)
adding: ods/SLList$Node.class(in = 441) (out= 294)(deflated 33%)
adding: ods/SLList.class(in = 2915) (out= 1417)(deflated 51%)
adding: ods/SSet.class(in = 647) (out= 316)(deflated 51%)
adding: ods/SString.class(in = 1161) (out= 643)(deflated 44%)
adding: ods/SVGTreap.class(in = 3923) (out= 2163)(deflated 44%)
adding: ods/ScapegoatTree$Node.class(in = 435) (out= 276)(deflated 36%)
adding: ods/ScapegoatTree.class(in = 3246) (out= 1635)(deflated 49%)
adding: ods/ScapegoatTree2.class(in = 1630) (out= 810)(deflated 50%)
adding: ods/SkiplistList$1SkiplistIterator.class(in = 1352) (out= 755)(deflated 44%)
adding: ods/SkiplistList$Node.class(in = 781) (out= 473)(deflated 39%)
adding: ods/SkiplistList.class(in = 3627) (out= 1953)(deflated 46%)
adding: ods/SkiplistRope$Node.class(in = 526) (out= 346)(deflated 34%)
adding: ods/SkiplistRope.class(in = 891) (out= 589)(deflated 33%)
adding: ods/SkiplistSSet$1SkiplistIterator.class(in = 1195) (out= 629)(deflated 47%)
adding: ods/SkiplistSSet$Finger.class(in = 768) (out= 487)(deflated 36%)
adding: ods/SkiplistSSet$Node.class(in = 716) (out= 429)(deflated 40%)
adding: ods/SkiplistSSet.class(in = 6028) (out= 3014)(deflated 50%)
adding: ods/SortedSSet$1BT.class(in = 610) (out= 375)(deflated 38%)
adding: ods/SortedSSet$1I.class(in = 622) (out= 378)(deflated 39%)
adding: ods/SortedSSet$1N.class(in = 454) (out= 311)(deflated 31%)
adding: ods/SortedSSet$1XFT.class(in = 608) (out= 376)(deflated 38%)
adding: ods/SortedSSet.class(in = 3476) (out= 1595)(deflated 54%)
adding: ods/Testum.class(in = 13528) (out= 5367)(deflated 60%)
adding: ods/Treap$Node.class(in = 419) (out= 279)(deflated 33%)
adding: ods/Treap.class(in = 2209) (out= 1138)(deflated 48%)
adding: ods/USet.class(in = 405) (out= 236)(deflated 41%)
adding: ods/USetMap$Entry.class(in = 1125) (out= 563)(deflated 49%)
adding: ods/USetMap.class(in = 1535) (out= 766)(deflated 50%)
adding: ods/USetSet.class(in = 1526) (out= 803)(deflated 47%)
adding: ods/Utils.class(in = 3424) (out= 1775)(deflated 48%)
adding: ods/VEBTree$Node.class(in = 427) (out= 290)(deflated 32%)
adding: ods/VEBTree.class(in = 2906) (out= 1633)(deflated 43%)
adding: ods/XFastTrie$1I.class(in = 619) (out= 379)(deflated 38%)
adding: ods/XFastTrie$1N.class(in = 420) (out= 290)(deflated 30%)
adding: ods/XFastTrie$Nöde.class(in = 614) (out= 383)(deflated 37%)
adding: ods/XFastTrie.class(in = 3638) (out= 1889)(deflated 48%)
adding: ods/YFastTrie$1.class(in = 743) (out= 432)(deflated 41%)
adding: ods/YFastTrie$1I.class(in = 619) (out= 378)(deflated 38%)
adding: ods/YFastTrie$2.class(in = 730) (out= 432)(deflated 40%)
adding: ods/YFastTrie$MIterator.class(in = 1575) (out= 811)(deflated 48%)
adding: ods/YFastTrie$Node.class(in = 453) (out= 288)(deflated 36%)
adding: ods/YFastTrie$Pair.class(in = 611) (out= 347)(deflated 43%)
adding: ods/YFastTrie$STreap.class(in = 1797) (out= 992)(deflated 44%)
adding: ods/YFastTrie.class(in = 5424) (out= 2576)(deflated 52%)
make[1]: Leaving directory `/home/vembu/work/projects/go/src/ods/java'
(cd latex ; make)
make[1]: Entering directory `/home/vembu/work/projects/go/src/ods/latex'
cd images ; make
make[2]: Entering directory `/home/vembu/work/projects/go/src/ods/latex/images'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/home/vembu/work/projects/go/src/ods/latex/images'
cd figs ; make
make[2]: Entering directory `/home/vembu/work/projects/go/src/ods/latex/figs'
ipetoipe -pdf 24rb.ipe
Document 24rb.ipe has 1 pages (3 views)
There were Latex errors.
make[2]: *** [24rb.pdf] Error 1
make[2]: Leaving directory `/home/vembu/work/projects/go/src/ods/latex/figs'
make[1]: *** [figs] Error 2
make[1]: Leaving directory `/home/vembu/work/projects/go/src/ods/latex'
make: *** [all] Error 2

Installed Packages : apt-get install texlive-latex-base perl ipe inkscape gnuplot pdftk default-jdk

**Comment by lam2mo** [comment]
Looks like Ubuntu 14.04 has a few other texlive-latex packages you could try. I'd suggest installing "texlive-latex-recommended" and "texlive-latex-extra". Maybe even "texlive-full".

**Comment by maknahar** [comment]
@lam2mo Installed "texlive-full" but same error.

**Comment by patmorin** [comment]
The problem is that LaTeX, when run by ipe, is not finding ods-colors.sty
.  On my installation of texlive, the easiest solution is to copy (or
better symlink) the file

ODSDIR/latex/ods-colors.sty

into

~/texmf/tex/latex/ods/ods-colors.sty

You may also have to texhash.

Pat

On Wed, Aug 12, 2015 at 9:55 AM, Mike L <notifications@github.com> wrote:

> Looks like Ubuntu 14.04 has a few other texlive-latex packages you could
> try. I'd suggest installing "texlive-latex-recommended" and
> "texlive-latex-extra". Maybe even "texlive-full".
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/patmorin/ods/issues/32#issuecomment-130314050>.
>



-- 
( ͡° ͜ʖ ͡°)

**Comment by EvanMisshula** [comment]
@patmorin Thank you for this wonderful book and all the effort you put into it.  I have put a copy of odd-colors.sty into my local library:

/Users/emisshula/Library/texmf/tex/latex/ods

If I load the figure into ..ipe.. and run latex from inside ..ipe..I get:

(/Users/emisshula/Library/texmf/tex/latex/ods/ods-colors.sty

! LaTeX Error: Option clash for package xcolor.

So it seems to find dos-color.sty.  I just don't know how to load it so it does not have this conflict.  Any hints are much appreciated.

**Comment by yalmar** [comment]
I don't know if all of you already solved this problem, But really the problem is with texlive installation, 
texlive-full doesn't resolve the problem, 
you must install two packages more
sudo apt-get install texlive-fonts-extra (kpfonts)
sudo apt-get install texlive-fonts-recommended (wasysym)
after I have had installed these, it works, but still have some errors (see below):

I couldn't open style file abbrvurl.bst
---line 37 of file ods-cpp.aux
 : \bibstyle{abbrvurl
 :                   }
I'm skipping whatever remains of this command
I found no style file---while reading file ods-cpp.aux
(There were 2 error messages)

**Comment by yalmar** [comment]
I forgot to thank @patmorin for his incredible work
