### ISSUE TITLE
Error in math statement ??

### ISSUE THREAD

**Issue by JTMartins** [patmorin/ods#41]
In page 10 there is the following mention
'When x is a negative integer, b^-x = 1/b^-x'

Shouldn't this be
When x is a negative integer, b^-x = 1/b^x

?

**Comment by patmorin** [comment]
I'm not seeing it.  In all the versions I looked at, it says, "When x is a negative integer, b^x=1/b^-x."  Maybe you're looking at an old version?

**Comment by JTMartins** [comment]
I will check. I'm reading a pdf version I've found.
But anyway although your math expression is correct, when we say that X is a negative number I understand we are are talking about b^-x (and not b^x).  I think that was my confusion as B^-x =1/b^x
