### ISSUE TITLE
height(u) on section 6.11 - binary tree

### ISSUE THREAD

**Issue by jaraujouerj** [patmorin/ods#64]
Hi. I think there is an error on function height(u), section 6.11, for binary trees. The right function must be
```
height(u)
  if u = nil then return -1
  return 1 + max(height(u.left), height(u.right))
```
in order to give the right answer. Thank you for your great work. I'm preparing a translation to brazilian portuguese from your book.

**Comment by patmorin** [comment]
Yes, that's a mistake in the pseudocode version.  I'll fix it during the next update.
